### ISSUE TITLE
Opinion: remove `timestamp` from event

### ISSUE THREAD

**Issue by adamgall** [decent-dao/contract-signer#1]
https://github.com/decent-dao/contract-signer/blob/c3ae85420ef6606973413df6977518a516f6b805/contracts/ContractSigner.sol#L16

Since this `timestamp` exists in an event, which are only available to clients, I suggest we remove it since reading an event from a client always allows us to reference the transaction that the event is included in, and that transaction object already has a (the same) timestamp within it.

**Comment by tbwebb22** [comment]
Ah yes, that makes sense. Will push up a commit to remove the timestamp
